/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LB' at '2017/6/8 Šå 12:21' with Gradle 2.14.1
 *
 * @author LB, @date 2017/6/8 Šå 12:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
